export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import "@/app/input.css";
import { NavBar } from "@/components/navbar";
import { Footer } from "@/components/footer";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     
      <body className="body ">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
